spring:
  datasource:
    url: jdbc:h2:file:./data/expensetracker
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

flyway:
  url: jdbc:h2:file:./data/expensetracker
  locations: classpath:db/migration
  username: sa
  password:

# JWT config - set a long random value in production (use env var or secret manager)
jwt:
  secret: change-me-to-a-long-random-secret-of-at-least-32-bytes
  expiration-ms: 86400000  # 24h


# TODO logging?

# TODO not add username and password to git?